# -*- coding: utf-8 -*-
"""python_142895.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kIY0ZDgRyV-RdiwBxqn2FBIUGmSQ6Qo5
"""
# import pandas
import pandas as pd
# import library for working on large, multi-dimensional arrays and matrices.
import numpy as np
import feature_1 as f1
import feature_2 as f2
import feature_3 as f3
import feature_4 as f4

# IMPORT DATA

# import csv file 'City Drive 2'
DATA = pd.read_csv("City Drive 2.csv")
print(DATA)

# Extract different latitude and longitude points.
PATH_LATS = np.array(DATA[' Latitude'])
PATH_LONG = np.array(DATA[' Longitude'])

# FEATURE 1
# Plot Path and Trip Details
f1.feature1(DATA, PATH_LATS, PATH_LONG)

# FEATURE 2
# Detect and Plot Harsh Accelerations
f2.feature2(DATA, PATH_LATS, PATH_LONG)

# FEATURE 3
# Detect and Plot Bad Road Condition
f3.feature3(DATA, PATH_LATS, PATH_LONG)

# FEATURE 4
# Fuel Consumption Waste
f4.feature4(DATA, PATH_LATS, PATH_LONG)
